def main_menu():
    print('\n Please select a dinosaur to learn more.')
    print(' Type (q) to exit.')
    print(' 1. Triceratops')
    print(' 2. Stegosaurus')
    print(' 3. Tyrannosaurus')
    print(' 4. Diplodocus')
    print(' 5. Coelophysis')
    print(' 6. Velociraptor')
    print(' 7. Ceratosaurus')
    print(' 8. Brachiosaurus')
    print(' 9. Microraptor')
    print('10. Albertosaurus')
    print('11. Utahraptor')
    print('12. Allosaurus')
    print('13. Ankylosaurus')
    print('14. Giraffatitan')
    print('15. Megalosaurus')
